image: Visual Studio 2017

# Skip build on normal pushes
skip_non_tags: true

artifacts:
  - path: godot\bin\*.exe
    name: GodotBinary

environment:
  BUILD_REVISION: official
  VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  PYTHON: C:\Python27
  ANGLE_SRC_PATH: C:\projects\godot-builds\angle
  matrix:
    - GD_PLATFORM: windows
      TOOLS: yes
      TARGET: release_debug
      ARCH: amd64
    - GD_PLATFORM: windows
      TOOLS: yes
      TARGET: release_debug
      ARCH: x86
    - GD_PLATFORM: windows
      TOOLS: no
      TARGET: release
      ARCH: amd64
    - GD_PLATFORM: windows
      TOOLS: no
      TARGET: release_debug
      ARCH: amd64
    - GD_PLATFORM: windows
      TOOLS: no
      TARGET: release
      ARCH: x86
    - GD_PLATFORM: windows
      TOOLS: no
      TARGET: release_debug
      ARCH: x86
    - GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release
      ARCH: amd64
    - GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release_debug
      ARCH: amd64
    - GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release
      ARCH: x86
    - GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release_debug
      ARCH: x86
    - GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release
      ARCH: amd64_arm
    - GD_PLATFORM: winrt
      TOOLS: no
      TARGET: release_debug
      ARCH: amd64_arm

install:
  - set "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python.exe -m pip install -U pip setuptools wheel
  - pip install scons
  - if defined VS call "%VS%" %ARCH%  # if defined - so we can also use mingw
  - git submodule update --init --recursive # download submodules
  - ps: >-
      If ($env:GD_PLATFORM -Match "winrt") {
        Start-FileDownload https://github.com/GodotBuilder/godot-builds/releases/download/_tools/angle.7z
        7z.exe x angle.7z
      }

before_build:
  - echo %BUILD_REVISION%
  - echo %GD_PLATFORM%
  - python --version
  - scons --version
  - cl.exe

build_script:
  - cd godot
  - for /f %%p in ('dir /b ..\patches') do git apply ..\patches\%%p
  - git rev-parse HEAD
  - scons platform=%GD_PLATFORM% target=%TARGET% tools=%TOOLS% progress=no warnings=no verbose=no

deploy:
  description: 'Godot binaries deployed by Travis CI and AppVeyor'
  provider: GitHub
  auth_token:
    secure: NkkgDdlKir3GGjwwtCX6B09Z0i1kYiUbV1QTFCdm7gyHSJbIFotCL7OqNt81r9sw
  artifact: GodotBinary
  on:
    appveyor_repo_tag: true
